; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28314.0 

	TITLE	D:\Hyperion\Hyperion Engine\zlib-1.2.11\inffast.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
