
using System;
using System.Collections.Generic;


namespace Hyperion
{
	public struct TextureImportState
	{
		public TextureFormat Format;
		public string Path;

		public List< TextureImportLOD > LODs;
	}

	public class TextureImportLOD
	{
		public uint RowSize;
		public uint Width;
		public uint Height;
		public byte[] Data;
		public bool Autogenerated;
		public string ImagePath;
		public ImageFormat SourceFormat;

		public TextureImportLOD()
		{
			RowSize = 0;
			Width = 0;
			Height = 0;
			Data = null;
			Autogenerated = false;
			ImagePath = null;
			SourceFormat = ImageFormat.NONE;
		}
	}
}